version: '2'

volumes:
  db_data: {}
  redis: {}

services:
  db:
    image: postgres:9.4
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env

  redis:
    image: redis:2
    volumes:
      - redis:/var/lib/redis/data
    restart: always

  web:
    image: civica-digital/urbem-puebla
    build: .
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    ports:
      - 5000:3000

  sidekiq:
    image: civica-digital/urbem-puebla
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    restart: always
    env_file:
      - ./.env
